# Configuración de análisis SonarQube local
sonar.projectKey=Avianca-EMSA
sonar.projectName=Avianca EMSA
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=sqp_52dd398de9643bc870f11b5b110ee619e21f2054
sonar.sourceEncoding=UTF-8
